apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ottoodo.apiname" . }}
  labels:
    app: {{ include "ottoodo.apiname" . }}
    instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ include "ottoodo.apiname" . }}
  minReplicas: {{.Values.api.replicaCount}}
  maxReplicas: {{.Values.api.hpa.maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{.Values.api.hpa.cpuUtilization}}