apiVersion: v1
kind: Service
metadata:
  name: {{ include "ottoodo.apiname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ottoodo.apiname" . }}
    helm.sh/chart: {{ include "ottoodo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
            ---
            apiVersion: ambassador/v0
            kind: Mapping
            name: {{ include "ottoodo.apiname" . }}_{{ .Release.Namespace  }}_mapping
            host: ossdemo.ottoo.com
            prefix: /api/
            rewrite: /api/
            service: {{ include "ottoodo.apiname" . }}.{{ .Release.Namespace  }}
            timeout_ms: 15000 #15 sec
            envoy_override:
                retry_policy:
                    retry_on: connect-failure
                    num_retries: 4  
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "ottoodo.apiname" . }}
    instance: {{ .Release.Name }}
