apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "ottoodo.uiname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ottoodo.uiname" . }}
    helm.sh/chart: {{ include "ottoodo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ottoodo.uiname" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ottoodo.uiname" . }}
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}         
          ports:
            - containerPort: {{ .Values.ui.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.containerPort }}
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.containerPort }}
            periodSeconds: 20
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
